{
    'name': 'Theme Zenith',
    'summary': 'The Ultimate High-Performance eCommerce Theme',
    'description': 'Advanced eCommerce theme for Tecnosoft.',
    'category': 'Theme/Ecommerce',
    'version': '18.0.2.0.0',
    'author': 'Tecnosoft 2025, C.A.',
    'website': 'https://www.tecnosoft.dev',
    'depends': ['website', 'website_sale', 'website_sale_comparison', 'website_sale_wishlist'],
    'data': [
        'security/ir.model.access.csv',
        'views/theme_templates.xml',
        'views/snippets.xml',
        'data/presets.xml',
        'views/website_views.xml',
        'views/sales_triggers.xml',
        'views/popups.xml',
        'views/brands.xml',
        'views/price_tracker.xml',
        'views/portal_templates.xml',
        'views/marketing_automation.xml',
        'views/performance_seo.xml',
        'views/quick_view.xml',
        'views/product_brand_views.xml',
        'views/product_label_views.xml',
        'views/product_size_guide_views.xml',
        'views/frequently_bought_templates.xml',
        'views/quick_order_templates.xml',
        'views/quote_templates.xml',
        'views/headers/header_zenith_v1.xml',
        'views/wishlist_comparison.xml',
        'views/variant_templates.xml',
        'views/checkout_templates.xml',
        'views/tecnosoft_branch_views.xml',
    ],
    'demo': [
        'data/demo_data.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'website_tecnosoft/static/src/scss/primary_variables.scss',
            'website_tecnosoft/static/src/scss/bootstrap_overridden.scss',
            'website_tecnosoft/static/src/scss/ecommerce.scss',
            'website_tecnosoft/static/src/scss/dynamic_snippets.scss',
            'website_tecnosoft/static/src/scss/ui_extras.scss',
            'website_tecnosoft/static/src/scss/hotspots.scss',
            'website_tecnosoft/static/src/scss/marketing_snippets.scss',
            'website_tecnosoft/static/src/scss/custom_headers.scss',
            'website_tecnosoft/static/src/scss/headers/header_zenith_v1.scss',
            'website_tecnosoft/static/src/scss/special_blocks.scss',
            'website_tecnosoft/static/src/scss/styles_engine.scss',
            'website_tecnosoft/static/src/scss/mega_menu.scss',
            'website_tecnosoft/static/src/scss/side_cart.scss',
            'website_tecnosoft/static/src/scss/product_sticky.scss',
            'website_tecnosoft/static/src/scss/animations.scss',
            'website_tecnosoft/static/src/scss/mobile_bar.scss',
            'website_tecnosoft/static/src/scss/wishlist_comparison.scss',
            'website_tecnosoft/static/src/scss/product_labels.scss',
            'website_tecnosoft/static/src/js/dynamic_snippets.js',
            'website_tecnosoft/static/src/js/options.js',
            'website_tecnosoft/static/src/js/side_cart.js',
            'website_tecnosoft/static/src/js/product_sticky.js',
            'website_tecnosoft/static/src/js/animations.js',
            'website_tecnosoft/static/src/js/sales_triggers.js',
            'website_tecnosoft/static/src/js/popups.js',
            'website_tecnosoft/static/src/js/price_tracker.js',
            'website_tecnosoft/static/src/js/quick_view.js',
            'website_tecnosoft/static/src/js/marketing_snippets.js',
            'website_tecnosoft/static/src/js/ajax_search.js',
            'website_tecnosoft/static/src/js/ajax_filters.js',
            'website_tecnosoft/static/src/js/recently_viewed.js',
            'website_tecnosoft/static/src/js/recently_viewed_snippet.js',
            'website_tecnosoft/static/src/js/price_slider.js',
            'website_tecnosoft/static/src/js/infinite_scroll.js',
            'website_tecnosoft/static/src/js/store_locator.js',
            'website_tecnosoft/static/src/js/countdown.js',
            'website_tecnosoft/static/src/js/complete_look.js',
            'website_tecnosoft/static/src/js/quick_order.js',
            'website_tecnosoft/static/src/js/branch_stock.js',
        ],
        'web.assets_frontend_minimal': [
            'website_tecnosoft/static/src/xml/dynamic_snippets.xml',
            'website_tecnosoft/static/src/xml/ajax_search.xml',
            'website_tecnosoft/static/src/xml/cart_upsell.xml',
        ],
        'web.assets_qweb': [
            'website_tecnosoft/static/src/xml/dynamic_snippets.xml',
            'website_tecnosoft/static/src/xml/ajax_search.xml',
            'website_tecnosoft/static/src/xml/cart_upsell.xml',
        ],
    },
    'images': [
        'static/description/tecnosoft_screenshot.png',
    ],
    'license': 'LGPL-3',
}
