{
    'name': 'Theme Zenith',
    'summary': 'The Ultimate High-Performance eCommerce Theme',
    'description': 'Advanced eCommerce theme for Zenith.',
    'category': 'Theme/Ecommerce',
    'version': '18.0.2.0.36',
    'author': 'Zenith 2025, C.A.',
    'website': 'https://www.zenith.dev',
    'post_init_hook': '_post_init_cleanup',
    'depends': ['website_sale_stock', 'website_sale_comparison', 'website_sale_wishlist', 'website_sale', 'website', 'web_editor'],
    'data': [
        'security/ir.model.access.csv',
        'data/emergency_fix.xml',
        'views/layout_overrides.xml',
        'views/res_config_settings_views.xml',
        'views/custom_styles.xml',
        'views/snippets.xml',
        'data/presets.xml',
        'views/website_views.xml',
        'views/sales_triggers.xml',
        'views/popups.xml',
        'views/brands.xml',
        'views/price_tracker.xml',
        'views/portal_templates.xml',
        'views/marketing_automation.xml',
        'views/performance_seo.xml',
        'views/quick_view.xml',
        'views/product_brand_views.xml',
        'views/product_label_views.xml',
        'views/product_size_guide_views.xml',
        'views/frequently_bought_templates.xml',
        'views/quick_order_templates.xml',
        'views/quote_templates.xml',
        'views/headers/header_zenith_v1.xml',
        'views/headers/header_zenith_v2.xml',
        'views/wishlist_comparison.xml',
        'views/variant_templates.xml',
        'views/checkout_templates.xml',
        'views/zenith_branch_views.xml',
        'views/website_sale_delivery.xml',
        'views/lottie_animations.xml',
        'views/product_seo_action.xml',
        'views/instagram_feed.xml',
        'views/footers/footer_zenith_v1.xml',
        'views/dynamic_menu.xml',
        'views/whatsapp_widget.xml',
        'views/product_tabs.xml',
        'views/buy_now.xml',
        'views/category_cards.xml',
        'views/multi_tab_products.xml',
        'views/comparison_drawer.xml',
        'views/comparison_page.xml',
        'views/flash_sales.xml',
        'views/theme_customizer.xml',
        'views/product_backend.xml',
        'views/shopping_list_templates.xml',
        'views/portal_addresses.xml',
    ],
    'demo': [
        'data/demo_data.xml',
    ],
    'assets': {
        'web.assets_frontend': [
            'theme_zenith/static/src/scss/primary_variables.scss',
            'theme_zenith/static/src/scss/ui_polish.scss',
            'theme_zenith/static/src/scss/bootstrap_overridden.scss',
            'theme_zenith/static/src/scss/ecommerce.scss',
            'theme_zenith/static/src/scss/dynamic_snippets.scss',
            'theme_zenith/static/src/scss/ui_extras.scss',
            'theme_zenith/static/src/scss/hotspots.scss',
            'theme_zenith/static/src/scss/marketing_snippets.scss',
            'theme_zenith/static/src/scss/custom_headers.scss',
            'theme_zenith/static/src/scss/headers/header_zenith_v1.scss',
            'theme_zenith/static/src/scss/headers/header_zenith_v2.scss',
            'theme_zenith/static/src/scss/headers/footer_zenith_v1.scss',
            'theme_zenith/static/src/scss/complete_look.scss',
            'theme_zenith/static/src/scss/comparison_drawer.scss',
            'theme_zenith/static/src/scss/flash_sales.scss',
            'theme_zenith/static/src/scss/social_proof.scss',
            'theme_zenith/static/src/scss/category_cards.scss',
            'theme_zenith/static/src/scss/multi_tab_products.scss',
            'theme_zenith/static/src/scss/product_page.scss',
            'theme_zenith/static/src/scss/special_blocks.scss',
            'theme_zenith/static/src/scss/styles_engine.scss',
            'theme_zenith/static/src/scss/mega_menu.scss',
            'theme_zenith/static/src/scss/side_cart.scss',
            'theme_zenith/static/src/scss/product_sticky.scss',
            'theme_zenith/static/src/scss/animations.scss',
            'theme_zenith/static/src/scss/mobile_bar.scss',
            'theme_zenith/static/src/scss/skeleton_loading.scss',
            'theme_zenith/static/src/scss/wishlist_comparison.scss',
            'theme_zenith/static/src/scss/product_labels.scss',
            'theme_zenith/static/src/scss/local_review.scss',
            'theme_zenith/static/src/scss/local_review.scss',
            'theme_zenith/static/src/scss/theme_customizer.scss',
            'theme_zenith/static/src/scss/dark_mode.scss',
            'theme_zenith/static/src/scss/zenith_cards.scss',
            'theme_zenith/static/src/js/emergency_hardening.js',
            'theme_zenith/static/src/js/dynamic_snippets.js',
            'theme_zenith/static/src/js/side_cart.js',
            'theme_zenith/static/src/js/product_sticky.js',
            'theme_zenith/static/src/js/animations.js',
            'theme_zenith/static/src/js/pwa_install.js',
            'theme_zenith/static/src/js/cart_upsell.js',
            'theme_zenith/static/src/js/dynamic_menu.js',
            'theme_zenith/static/src/js/sales_triggers.js',
            'theme_zenith/static/src/js/popups.js',
            'theme_zenith/static/src/js/price_tracker.js',
            'theme_zenith/static/src/js/quick_view.js',
            'theme_zenith/static/src/js/marketing_snippets.js',
            'theme_zenith/static/src/js/ajax_search.js',
            'theme_zenith/static/src/js/ajax_filters.js',
            'theme_zenith/static/src/js/price_slider.js',
            'theme_zenith/static/src/js/infinite_scroll.js',
            'theme_zenith/static/src/js/store_locator.js',
            'theme_zenith/static/src/js/countdown.js',
            'theme_zenith/static/src/js/comparison_drawer.js',
            'theme_zenith/static/src/js/wishlist_animation.js',
            'theme_zenith/static/src/js/social_proof.js',
            'theme_zenith/static/src/js/complete_look.js',
            'theme_zenith/static/src/js/buy_now.js',
            'theme_zenith/static/src/js/quick_order.js',
            'theme_zenith/static/src/js/variant_preview.js',
            'theme_zenith/static/src/js/branch_stock.js',
            'theme_zenith/static/src/js/branch_stock.js',
            'theme_zenith/static/src/js/theme_customizer.js',
            'theme_zenith/static/src/js/add_to_list.js',
            'theme_zenith/static/src/js/dark_mode.js',
            'theme_zenith/static/src/js/address_selector.js',
            'theme_zenith/static/src/xml/dynamic_snippets.xml',
            'theme_zenith/static/src/xml/ajax_search.xml',
            'theme_zenith/static/src/xml/cart_upsell.xml',
        ],
        'web.assets_frontend_minimal': [
        ],
        'web.assets_backend': [
            'theme_zenith/static/src/js/ai_generator.js',
            'theme_zenith/static/src/xml/ai_generator.xml',
        ],
        'website.assets_wysiwyg': [
            'theme_zenith/static/src/js/options.js',
        ],
    },
    'images': [
        'static/description/zenith_screenshot.png',
    ],
    'license': 'LGPL-3',
}
